### ISSUE TITLE
Manual upgrade failed: 'sqlite3.OperationalError: unable to open database file'

### ISSUE THREAD

**Issue by Ciphergyst** [mynodebtc/mynode#343]
+ sudo -u bitcoin pipenv run flask migrate
Loading .env environment variables…
Traceback (most recent call last):
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/mynode/lnbits/lnbits/__init__.py", line 76, in migrate_databases
    core_migrations.migrate()
  File "/opt/mynode/lnbits/lnbits/core/migrations.py", line 74, in migrate
    with open_db() as db:
  File "/opt/mynode/lnbits/lnbits/db.py", line 38, in open_db
    return Database(db_path=db_path)
  File "/opt/mynode/lnbits/lnbits/db.py", line 10, in __init__
    self.connection = sqlite3.connect(db_path)
sqlite3.OperationalError: unable to open database file

**Comment by Ciphergyst** [comment]
import os
import sqlite3

from .settings import LNBITS_DATA_FOLDER


class Database:
    def __init__(self, db_path: str):
        self.path = db_path
        self.connection = sqlite3.connect(db_path)
        self.connection.row_factory = sqlite3.Row
        self.cursor = self.connection.cursor()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.cursor.close()
        self.connection.close()

    def fetchall(self, query: str, values: tuple = ()) -> list:
        """Given a query, return cursor.fetchall() rows."""
        self.cursor.execute(query, values)
        return self.cursor.fetchall()

    def fetchone(self, query: str, values: tuple = ()):
        self.cursor.execute(query, values)
        return self.cursor.fetchone()

    def execute(self, query: str, values: tuple = ()) -> None:
        """Given a query, cursor.execute() it."""
        self.cursor.execute(query, values)
        self.connection.commit()


def open_db(db_name: str = "database") -> Database:
    db_path = os.path.join(LNBITS_DATA_FOLDER, f"{db_name}.sqlite3")
    return Database(db_path=db_path)


def open_ext_db(extension_name: str) -> Database:
    return open_db(f"ext_{extension_name}")

**Comment by Ciphergyst** [comment]
A reboot seemed to solve this particular issue but remote ssh was closed by systemctl restart dhcpd.service
Maybe recommend screen to prevent pipe interrupts
