### ISSUE TITLE
Install myNode on a normal amd64 laptop/pc

### ISSUE THREAD

**Issue by maltokyo** [mynodebtc/mynode#355]
I find the requirements that I have to buy a certain (cheap, unreliable) Pi or another single-board computer, or use Virtualbox unacceptable when I have some old spare machines already lying around with much better specs than the "standard" recommendations from myNode.

I am working on getting it working on a normal amd64 laptop/pc running stock Debian 10.

If anyone already did it, I hope you could share the full steps.

If not, I will work it out, and share here if there is any interest from anyone else(?)

**Comment by zndtoshi** [comment]
Hello maltokyo. Actually I was interested in something similar but have looking for having a bootable usb that gets mynode as a standalone OS (with linux in the back) on a regular pc. Do you think this is possible? If you are interested in working on such a think I could chip it with a bit of funds.

**Comment by maltokyo** [comment]
This would be impractical, as myNode requires a 1TB hard drive attached as well.  Also needs to be on majority of the time to stay synched. What's the use case?

**Comment by zndtoshi** [comment]
I think it's similar to what you wanted, but it's easier to install for a normal user. The average user doesn't know how to install debian and so on so if you give him one iso that he can flash on an usb stick and he can plug inside an old computer and just erase windows and install that Mynode os on top that would be very easy for him. It's just a suggestion I don't know how easy/hard it is to pull this off.

**Comment by maltokyo** [comment]
I got you now. I thought you wanted to run it from the live usb.

**Comment by zndtoshi** [comment]
Would you be interested in such a project?

**Comment by maltokyo** [comment]
Well keeping it up to date would be the hardest part. I can make a write-up on everything including how to install debian. It took me only an hour or so

**Comment by maltokyo** [comment]
Here is my draft tutorial, anyone wants to test?  It worked for me!    But maybe I missed to document something, or you could propose better wording?  After we are good to go, I will make a PR for a wiki entry.

I have run this for two days now, and all systems stable and working!

=============================

# Setup Base Image (Debian)

1. Setup Base OS

   Install Debian 10.4 Net-install via CD

   URL: [https://www.debian.org/CD/netinst/](https://www.debian.org/CD/netinst/)

   Follow instructions:

     - Graphical Install
     - English, US, American English
     - Hostname: myNode
     - Domain Name: <LEAVE_EMPTY>
     - Root Password: bolt
     - Full Name: myNode
     - Username: mynode
     - Password: bolt
     - Timezone: Central
     - Partition: Guided Use Entire Disk, Continue with defaults and Yes for write changes to disk
     - CDs and Packages: No, Next, Next (if you get this step, for me it had an error and I skipped it)
     - Software Selection: No GUI, No Print Server, Add SSH Server
     - Install Grub: Yes, /dev/sda (it wont ask if that is your only OS, it will do automatically)
     - Install Complete: Continue

2. Login as root / bolt


- Turn on the network by editing the interfaces file (you need to find out the name of your network card first, it changes from one hardware to another)
nano /etc/network/interfaces

# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# add below part for mynode
auto wl0 #replace with your interface name, in the case below it is a wifi card
iface wl0 inet dhcp
wpa-psk 12345678 #your password for wifi
wpa-ssid stayout #your wifi network name

- Change ssh config to allow Root Login if you need to login from another machine, ignore this step if you do all from the same machine
and then
```sh
service ssh reload
```

3. Install basic Software needed

   ```sh
   apt-get -y install sudo tmux make rsync curl gpg
   useradd -p $(openssl passwd -1 bolt) -m -s /bin/bash admin
   adduser admin sudo
   ```

4. Delete mynode user

   ```sh
   deluser mynode
   rm -rf /home/mynode
   exit
   ```

5. Login to machine as admin / bolt

6. Delete root password

   ```sh
   sudo passwd -d root
   ```

7. Update debian packages

   ```sh
   sudo apt-get -y update
   sudo apt-get -y upgrade
   ```

8. Sync

   ```sh
   sync
   ```

9. Make image now (if imaging)

10. Reboot

11. Follow this down to the step called "Run make start_file_server":
https://github.com/mynodebtc/mynode#upgrading-your-mynode

then go to this one:
https://github.com/mynodebtc/mynode#convert-new-device-to-run-mynode
So I ran:
```sh
sudo make setup_new_debian
```
(I am not sure if i needed to do this line ABOVE here, and not sure what it did, I think it just downloads virtualbox image)

12. comment out these lines in setup/setup_device.sh as they make device unkown when we already know it is amd64
#if [ $IS_UNKNOWN = 1 ]; then
#    echo "UNKNOWN DEVICE TYPE"
#    exit 1
#fi

Also:
lndbits .env file path is wrong (it thinks you have the image, but it is whereever you cloned your GIT to), so first fix this part to a path that exists
```sh
   # Copy over config file
    cp /usr/share/mynode/lnbits.env /opt/mynode/lnbits/.env
```

13.
Run this from whereever mynode git base is (cd into it first) and replace IP address with IP of your own machine:
```sh
sudo ./setup/setup_device.sh 192.168.X.X
```


14. After reboot
Did this again just for good measure, but I dont think I needed:
https://github.com/mynodebtc/mynode#upgrading-your-mynode

**Comment by maltokyo** [comment]
When some other people verify it, we can add here:

https://github.com/mynodebtc/mynode/wiki

**Comment by maltokyo** [comment]
I added in wiki now, as I had time: 

https://github.com/mynodebtc/mynode/wiki/Alternate-ways-to-setup-myNode

Any further changes or enhancements, please change there directly!

**Comment by beeri0** [comment]
@maltokyo 
my setup script stops with 
`+ sudo -u bitcoin pipenv run flask migrate 

Loading .env environment variables…
https://localhost:10080
Traceback (most recent call last):
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/mynode/lnbits/lnbits/__init__.py", line 76, in migrate_databases
    core_migrations.migrate()
  File "/opt/mynode/lnbits/lnbits/core/migrations.py", line 74, in migrate
    with open_db() as db:
  File "/opt/mynode/lnbits/lnbits/db.py", line 38, in open_db
    return Database(db_path=db_path)
  File "/opt/mynode/lnbits/lnbits/db.py", line 10, in __init__
    self.connection = sqlite3.connect(db_path)
sqlite3.OperationalError: unable to open database file`

Do u have an idea how to fix it ? or what the problem could be ?

**Comment by maltokyo** [comment]
Yes. I actually think this is a bug in the setup code. As the path is hardcoded for lnbits. 

Please see this part of my guide:

```
lndbits .env file path is wrong (it thinks you have the image, but it is whereever you cloned your GIT to), so first fix this part to a path that exists
```

Does it make sense?

**Comment by maltokyo** [comment]
@beeri0 to be more clear:

In these files: https://github.com/mynodebtc/mynode/search?q=cp+%2Fusr%2Fshare%2Fmynode%2Flnbits.env&unscoped_q=cp+%2Fusr%2Fshare%2Fmynode%2Flnbits.env

Change this:

`cp /usr/share/mynode/lnbits.env`

To the path of wherever your git clone directory is (exact path to lnbits.env) because, you do not have it in /usr/share yet at this stage of the install, as far as I could see.

If someone knows why it is only this file that gets caught, and not every other file that is supposed to be in /usr/share, please let me know...

**Comment by tehelsper** [comment]
It would be best if the the laptop install was updated to "install" myNode so that paths like /usr/share/mynode/lnbits.env are the correct path. Otherwise, there will likely be may failures.

I had some suggestions in the setup_new_other and setup_new_debian scripts.

**Comment by beeri0** [comment]
My paths looks like this
`cp /home/admin/mynode/rootfs/standard/usr/share/mynode/lnbits.env /opt/mynode/lnbits/.env `

**Comment by beeri0** [comment]
Ok got it now. 

I needed to change the values  in lnbits.env 

I change all /mnt/hdd/mynode/lnbits values to /opt/mynode/lnbits

**Comment by maltokyo** [comment]
This setup works for me, but I want to install a single SSD internally (1TB) to run everything.  However, it still requires "external USB HDD".  Any ideas what to change to get it to install EVERYTHING on internal SSD?

**Comment by tehelsper** [comment]
It would be pretty difficult to get everything working on a system with a single drive. It might be quick to hack something to get it to run, but quite a few of the settings rely on a separate drive.

- Factory reset
- Backup scripts may run but would be useless (backing up to same drive)
- No way to re-install the OS in case of failures

I don't really recommend it.

Tips (not recommended)
- Comment out the drive mount logic in mynode_startup.sh
- Make a folder named /mnt/hdd/mynode

That might get it up and running.

**Comment by howTOdoIT2** [comment]
> 
> 
> This setup works for me, but I want to install a single SSD internally (1TB) to run everything. However, it still requires "external USB HDD". Any ideas what to change to get it to install EVERYTHING on internal SSD?

Same here, I have a laptop with 1 terra hdd  and I wanna run mynode standalone not virtual machine

**Comment by maltokyo** [comment]
@howTOdoIT2  I tried the "tips" above with my tutorial/wiki entry procedure, and everything works for me.  Did you get some errors?

**Comment by howTOdoIT2** [comment]
> 
> 
> @howTOdoIT2 I tried the "tips" above with my tutorial/wiki entry procedure, and everything works for me. Did you get some errors?

is your disk drive (ssd/hdd) internal or external ?
did you run the OS from SD card  or from your disk drive?

**Comment by maltokyo** [comment]
One single 1tb SSD

**Comment by howTOdoIT2** [comment]
> 
> 
> One single 1tb SSD

then why you wrote this ?:

```
 maltokyo commented on Aug 2

This setup works for me, but I want to install a single SSD internally (1TB) to run everything. However, it still requires "external USB HDD". Any ideas what to change to get it to install EVERYTHING on internal SSD?
```

**Comment by maltokyo** [comment]
Just make a mount point called /mnt/hdd

**Comment by howTOdoIT2** [comment]
> 
> 
> Just make a mount point called /mnt/hdd

how about you make  a fresh new guide ,maybe a youtube tutorial , **how to install mynode on laptop/PC**  
how about that bro?

**Comment by second2falcon** [comment]
I get this error after starting to run the setup_device.sh script:
`Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-pip

E: Package 'python-pip' has no installation candidate`

Any ideas what could fix this/what the problem is?

**Comment by second2falcon** [comment]
> > I get this error after starting to run the setup_device.sh script: `Note, selecting 'python-dev-is-python2' instead of 'python-dev'` `Package python-pip is not available, but is referred to by another package.` `This may mean that the package is missing, has been obsoleted, or` `is only available from another source` `However the following packages replace it:` ` python3-pip`
> > `E: Package 'python-pip' has no installation candidate`
> > Any ideas what could fix this/what the problem is?
> 
> do not waste time with myNode! use umbrel is free, and work great

I tried it, but it does not work at all. Also there is no error.

**Comment by second2falcon** [comment]
Got it to work now. For anyone who tries this in the future, in the wiki it should say that you need to use debian BUSTER (Debian 10). It does not work with Debian 11. Also there is 1 thing in the script which (atleast me) forced to enter the password for the joinmarket user. I needed to change the scrypt so that there actually was one.

**Comment by oculusit** [comment]
> I find the requirements that I have to buy a certain (cheap, unreliable) Pi or another single-board computer, or use Virtualbox unacceptable when I have some old spare machines already lying around with much better specs than the "standard" recommendations from myNode.
> 
> I am working on getting it working on a normal amd64 laptop/pc running stock Debian 10.
> 
> If anyone already did it, I hope you could share the full steps.
> 
> If not, I will work it out, and share here if there is any interest from anyone else(?)

I find a simple way to deploy mynode on a normale PC and I described in my site today. Sorry Is in italian language but google will help you.
https://www.oculus.it/oculusblog/it/btc-core-o-mynode-prendi-il-controllo-della-tua-rete-bitcoin/

**Comment by howTOdoIT2** [comment]
stop using this node is shit..better use umbrel is free and work great https://getumbrel.com/ 
you can install it on a raspberry pi or a amd64 cpu

**Comment by second2falcon** [comment]
> > I find the requirements that I have to buy a certain (cheap, unreliable) Pi or another single-board computer, or use Virtualbox unacceptable when I have some old spare machines already lying around with much better specs than the "standard" recommendations from myNode.
> 
> > 
> 
> > I am working on getting it working on a normal amd64 laptop/pc running stock Debian 10.
> 
> > 
> 
> > If anyone already did it, I hope you could share the full steps.
> 
> > 
> 
> > If not, I will work it out, and share here if there is any interest from anyone else(?)
> 
> 
> 
> I find a simple way to deploy mynode on a normal PC and I described in my site today. Sorry Is in italian language but google will help you.
> 
> https://www.oculus.it/oculusblog/it/btc-core-o-mynode-prendi-il-controllo-della-tua-rete-bitcoin/
> 
> 
> 
> Simply get the ova file and install It. Then convert the vdi file into img format and use it to write into a disk. It boots up magically.

Should I do one in English and/or German and Dutch?

**Comment by tehelsper** [comment]
Yeah, that'd be awesome. You gave me a really good idea. I bet I could easily make an image that could be flashed to a USB thumbdrive (or any internal drive) to boot off of. It's basically what you did, but you wouldn't need to go through the steps of creating the .img file from VDI yourself.

I could probably even just extract the one like you did and post it as a download. I'd like to test the boot-from-usb idea though since that would let people try it out pretty easily and I wouldn't have to make a whole live-CD installer type thing.

**Comment by howTOdoIT2** [comment]
just use umbrel node

**Comment by oculusit** [comment]
> Should I do one in English and/or German and Dutch?

Yes,you can do It!

**Comment by oculusit** [comment]
> Yeah, that'd be awesome. You gave me a really good idea. I bet I could easily make an image that could be flashed to a USB thumbdrive (or any internal drive) to boot off of. It's basically what you did, but you wouldn't need to go through the steps of creating the .img file from VDI yourself.
> 

Good idea!!

If the owner agree to this I think you can do It. Anyway all medium level Linux users can do itself by converting the vdi losing a couple of time.
