### ISSUE TITLE
LND won't progress past 'DB Loading...' - RPi4

### ISSUE THREAD

**Issue by asperks** [mynodebtc/mynode#363]
In a previous issue it was determined that there was an issue of directory creation : https://github.com/mynodebtc/mynode/issues/356

Now that the re-install of LND works, it still doesn't progress to operational.  After installing LND from the setup menu, it hangs with a message of "DB Loading..." on the LND tile.  I've attempted to re-install it several times, and it fails at the same point.

Is there anyway to progress this?

**Comment by tehelsper** [comment]
Just to make sure, if you run "lnd --version" does it show 10.3 after the re-install?

If so, what does the log for lnd say on the status page?

**Comment by asperks** [comment]
Version is now 0.10.3
```
lncli version 0.10.3-beta commit=v0.10.3-beta
```
The tile on the home screen : https://imgur.com/a/GrbTEc1

This is the LND log from the status page.
```
-- Logs begin at Tue 2020-07-21 21:40:47 CDT, end at Tue 2020-07-21 22:17:12 CDT. --
Jul 21 22:16:59 myNode systemd[1]: Failed to start LND Lightning Daemon.
Jul 21 22:16:59 myNode systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 21 22:16:59 myNode systemd[1]: lnd.service: Start request repeated too quickly.
Jul 21 22:16:59 myNode systemd[1]: Stopped LND Lightning Daemon.
Jul 21 22:16:59 myNode systemd[1]: lnd.service: Scheduled restart job, restart counter is at 5.
Jul 21 22:16:59 myNode systemd[1]: lnd.service: Service RestartSec=1s expired, scheduling restart.
Jul 21 22:16:58 myNode systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 21 22:16:58 myNode systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 21 22:16:58 myNode lnd[22372]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/db.go:1001 +0x108
Jul 21 22:16:58 myNode lnd[22372]: created by go.etcd.io/bbolt.(*DB).freepages
Jul 21 22:16:58 myNode lnd[22372]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/db.go:1003 +0xcc
Jul 21 22:16:58 myNode lnd[22372]: go.etcd.io/bbolt.(*DB).freepages.func2(0x325a240)
Jul 21 22:16:58 myNode lnd[22372]: goroutine 38 [running]:
Jul 21 22:16:58 myNode lnd[22372]: panic: freepages: failed to get all reachable pages (page 8055: multiple references)
Jul 21 22:16:58 myNode lnd[22372]: 2020-07-21 22:16:58.730 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 21 22:16:58 myNode lnd[22372]: 2020-07-21 22:16:58.730 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 21 22:16:58 myNode lnd[22372]: 2020-07-21 22:16:58.730 [INF] LTND: Version: 0.10.3-beta commit=v0.10.3-beta, build=production, logging=default
Jul 21 22:16:58 myNode lnd[22372]: Automatically obtained bitcoind's RPC credentials
Jul 21 22:16:58 myNode lnd[22372]: Attempting automatic RPC configuration to bitcoind
Jul 21 22:16:58 myNode systemd[1]: Started LND Lightning Daemon.
Jul 21 22:16:58 myNode lnd[22370]: + exit 0
Jul 21 22:16:58 myNode lnd[22370]: }
Jul 21 22:16:58 myNode lnd[22370]:   "warnings": ""
Jul 21 22:16:58 myNode lnd[22370]:   },
Jul 21 22:16:58 myNode lnd[22370]:     }
Jul 21 22:16:58 myNode lnd[22370]:       "height": 481824
Jul 21 22:16:58 myNode lnd[22370]:       "active": true,
Jul 21 22:16:58 myNode lnd[22370]:       "type": "buried",
Jul 21 22:16:58 myNode lnd[22370]:     "segwit": {
Jul 21 22:16:58 myNode lnd[22370]:     },
Jul 21 22:16:58 myNode lnd[22370]:       "height": 419328
Jul 21 22:16:58 myNode lnd[22370]:       "active": true,
Jul 21 22:16:58 myNode lnd[22370]:       "type": "buried",
Jul 21 22:16:58 myNode lnd[22370]:     "csv": {
Jul 21 22:16:58 myNode lnd[22370]:     },
Jul 21 22:16:58 myNode lnd[22370]:       "height": 388381
Jul 21 22:16:58 myNode lnd[22370]:       "active": true,
Jul 21 22:16:58 myNode lnd[22370]:       "type": "buried",
Jul 21 22:16:58 myNode lnd[22370]:     "bip65": {
Jul 21 22:16:58 myNode lnd[22370]:     },
Jul 21 22:16:58 myNode lnd[22370]:       "height": 363725
Jul 21 22:16:58 myNode lnd[22370]:       "active": true,
Jul 21 22:16:58 myNode lnd[22370]:       "type": "buried",
Jul 21 22:16:58 myNode lnd[22370]:     "bip66": {
Jul 21 22:16:58 myNode lnd[22370]:     },
Jul 21 22:16:58 myNode lnd[22370]:       "height": 227931
Jul 21 22:16:58 myNode lnd[22370]:       "active": true,
Jul 21 22:16:58 myNode lnd[22370]:       "type": "buried",
Jul 21 22:16:58 myNode lnd[22370]:     "bip34": {
Jul 21 22:16:58 myNode lnd[22370]:   "softforks": {
Jul 21 22:16:58 myNode lnd[22370]:   "pruned": false,
Jul 21 22:16:58 myNode lnd[22370]:   "size_on_disk": 328221488089,
Jul 21 22:16:58 myNode lnd[22370]:   "chainwork": "00000000000000000000000000000000000000001193a2e4d5960ab9e1153a46",
Jul 21 22:16:58 myNode lnd[22370]:   "initialblockdownload": false,
Jul 21 22:16:58 myNode lnd[22370]:   "verificationprogress": 0.9999922637962392,
Jul 21 22:16:58 myNode lnd[22370]:   "mediantime": 1595384395,
Jul 21 22:16:58 myNode lnd[22370]:   "difficulty": 17345948872516.06,
Jul 21 22:16:58 myNode lnd[22370]:   "bestblockhash": "00000000000000000000c485f9cea96d341ab9fa74134990a989d11a6c88f67b",
Jul 21 22:16:58 myNode lnd[22370]:   "headers": 640225,
Jul 21 22:16:58 myNode lnd[22370]:   "blocks": 640225,
Jul 21 22:16:58 myNode lnd[22370]:   "chain": "main",
Jul 21 22:16:58 myNode lnd[22370]: {
Jul 21 22:16:58 myNode lnd[22370]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
Jul 21 22:16:58 myNode lnd[22370]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Jul 21 22:16:58 myNode lnd[22370]: Checking if Bitcoin is synced...
Jul 21 22:16:58 myNode lnd[22370]: + echo 'Checking if Bitcoin is synced...'
Jul 21 22:16:58 myNode lnd[22370]: + set -e
Jul 21 22:16:58 myNode lnd[22367]: Not shutting down!
Jul 21 22:16:58 myNode lnd[22367]: Checking if device is shutting down...
Jul 21 22:16:58 myNode systemd[1]: Starting LND Lightning Daemon...
Jul 21 22:16:58 myNode systemd[1]: Stopped LND Lightning Daemon.
Jul 21 22:16:58 myNode systemd[1]: lnd.service: Scheduled restart job, restart counter is at 4.
Jul 21 22:16:58 myNode systemd[1]: lnd.service: Service RestartSec=1s expired, scheduling restart.
Jul 21 22:16:57 myNode systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 21 22:16:57 myNode systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 21 22:16:57 myNode lnd[22353]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/db.go:1001 +0x108
Jul 21 22:16:57 myNode lnd[22353]: created by go.etcd.io/bbolt.(*DB).freepages
Jul 21 22:16:57 myNode lnd[22353]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/db.go:1003 +0xcc
Jul 21 22:16:57 myNode lnd[22353]: go.etcd.io/bbolt.(*DB).freepages.func2(0x396c600)
Jul 21 22:16:57 myNode lnd[22353]: goroutine 26 [running]:
Jul 21 22:16:57 myNode lnd[22353]: panic: freepages: failed to get all reachable pages (page 8055: multiple references)
Jul 21 22:16:57 myNode lnd[22353]: 2020-07-21 22:16:57.188 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 21 22:16:57 myNode lnd[22353]: 2020-07-21 22:16:57.188 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 21 22:16:57 myNode lnd[22353]: 2020-07-21 22:16:57.187 [INF] LTND: Version: 0.10.3-beta commit=v0.10.3-beta, build=production, logging=default
Jul 21 22:16:57 myNode lnd[22353]: Automatically obtained bitcoind's RPC credentials
Jul 21 22:16:57 myNode lnd[22353]: Attempting automatic RPC configuration to bitcoind
Jul 21 22:16:57 myNode systemd[1]: Started LND Lightning Daemon.
Jul 21 22:16:57 myNode lnd[22351]: + exit 0
Jul 21 22:16:57 myNode lnd[22351]: }
Jul 21 22:16:57 myNode lnd[22351]:   "warnings": ""
Jul 21 22:16:57 myNode lnd[22351]:   },
Jul 21 22:16:57 myNode lnd[22351]:     }
Jul 21 22:16:57 myNode lnd[22351]:       "height": 481824
Jul 21 22:16:57 myNode lnd[22351]:       "active": true,
Jul 21 22:16:57 myNode lnd[22351]:       "type": "buried",
Jul 21 22:16:57 myNode lnd[22351]:     "segwit": {
Jul 21 22:16:57 myNode lnd[22351]:     },
Jul 21 22:16:57 myNode lnd[22351]:       "height": 419328
Jul 21 22:16:57 myNode lnd[22351]:       "active": true,
Jul 21 22:16:57 myNode lnd[22351]:       "type": "buried",
Jul 21 22:16:57 myNode lnd[22351]:     "csv": {
Jul 21 22:16:57 myNode lnd[22351]:     },
Jul 21 22:16:57 myNode lnd[22351]:       "height": 388381
Jul 21 22:16:57 myNode lnd[22351]:       "active": true,
Jul 21 22:16:57 myNode lnd[22351]:       "type": "buried",
Jul 21 22:16:57 myNode lnd[22351]:     "bip65": {
Jul 21 22:16:57 myNode lnd[22351]:     },
Jul 21 22:16:57 myNode lnd[22351]:       "height": 363725
Jul 21 22:16:57 myNode lnd[22351]:       "active": true,
Jul 21 22:16:57 myNode lnd[22351]:       "type": "buried",
Jul 21 22:16:57 myNode lnd[22351]:     "bip66": {
Jul 21 22:16:57 myNode lnd[22351]:     },
Jul 21 22:16:57 myNode lnd[22351]:       "height": 227931
Jul 21 22:16:57 myNode lnd[22351]:       "active": true,
Jul 21 22:16:57 myNode lnd[22351]:       "type": "buried",
Jul 21 22:16:57 myNode lnd[22351]:     "bip34": {
Jul 21 22:16:57 myNode lnd[22351]:   "softforks": {
Jul 21 22:16:57 myNode lnd[22351]:   "pruned": false,
Jul 21 22:16:57 myNode lnd[22351]:   "size_on_disk": 328221488089,
Jul 21 22:16:57 myNode lnd[22351]:   "chainwork": "00000000000000000000000000000000000000001193a2e4d5960ab9e1153a46",
Jul 21 22:16:57 myNode lnd[22351]:   "initialblockdownload": false,
Jul 21 22:16:57 myNode lnd[22351]:   "verificationprogress": 0.9999922697979026,
Jul 21 22:16:57 myNode lnd[22351]:   "mediantime": 1595384395,
Jul 21 22:16:57 myNode lnd[22351]:   "difficulty": 17345948872516.06,
Jul 21 22:16:57 myNode lnd[22351]:   "bestblockhash": "00000000000000000000c485f9cea96d341ab9fa74134990a989d11a6c88f67b",
Jul 21 22:16:57 myNode lnd[22351]:   "headers": 640225,
Jul 21 22:16:57 myNode lnd[22351]:   "blocks": 640225,
Jul 21 22:16:57 myNode lnd[22351]:   "chain": "main",
Jul 21 22:16:57 myNode lnd[22351]: {
Jul 21 22:16:57 myNode lnd[22351]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
Jul 21 22:16:57 myNode lnd[22351]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Jul 21 22:16:57 myNode lnd[22351]: Checking if Bitcoin is synced...
Jul 21 22:16:57 myNode lnd[22351]: + echo 'Checking if Bitcoin is synced...'
Jul 21 22:16:57 myNode lnd[22351]: + set -e
Jul 21 22:16:56 myNode lnd[22348]: Not shutting down!
Jul 21 22:16:56 myNode lnd[22348]: Checking if device is shutting down...
Jul 21 22:16:56 myNode systemd[1]: Starting LND Lightning Daemon...
Jul 21 22:16:56 myNode systemd[1]: Stopped LND Lightning Daemon.
Jul 21 22:16:56 myNode systemd[1]: lnd.service: Scheduled restart job, restart counter is at 3.
Jul 21 22:16:56 myNode systemd[1]: lnd.service: Service RestartSec=1s expired, scheduling restart.
Jul 21 22:16:55 myNode systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 21 22:16:55 myNode systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 21 22:16:55 myNode lnd[22336]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/db.go:1001 +0x108
Jul 21 22:16:55 myNode lnd[22336]: created by go.etcd.io/bbolt.(*DB).freepages
Jul 21 22:16:55 myNode lnd[22336]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/db.go:1003 +0xcc
Jul 21 22:16:55 myNode lnd[22336]: go.etcd.io/bbolt.(*DB).freepages.func2(0x2cc61c0)
Jul 21 22:16:55 myNode lnd[22336]: goroutine 21 [running]:
Jul 21 22:16:55 myNode lnd[22336]: panic: freepages: failed to get all reachable pages (page 8055: multiple references)
Jul 21 22:16:55 myNode lnd[22336]: 2020-07-21 22:16:55.719 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 21 22:16:55 myNode lnd[22336]: 2020-07-21 22:16:55.719 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 21 22:16:55 myNode lnd[22336]: 2020-07-21 22:16:55.718 [INF] LTND: Version: 0.10.3-beta commit=v0.10.3-beta, build=production, logging=default
Jul 21 22:16:55 myNode lnd[22336]: Automatically obtained bitcoind's RPC credentials
Jul 21 22:16:55 myNode lnd[22336]: Attempting automatic RPC configuration to bitcoind
Jul 21 22:16:55 myNode systemd[1]: Started LND Lightning Daemon.
Jul 21 22:16:55 myNode lnd[22333]: + exit 0
Jul 21 22:16:55 myNode lnd[22333]: }
Jul 21 22:16:55 myNode lnd[22333]:   "warnings": ""
Jul 21 22:16:55 myNode lnd[22333]:   },
Jul 21 22:16:55 myNode lnd[22333]:     }
Jul 21 22:16:55 myNode lnd[22333]:       "height": 481824
Jul 21 22:16:55 myNode lnd[22333]:       "active": true,
Jul 21 22:16:55 myNode lnd[22333]:       "type": "buried",
Jul 21 22:16:55 myNode lnd[22333]:     "segwit": {
Jul 21 22:16:55 myNode lnd[22333]:     },
Jul 21 22:16:55 myNode lnd[22333]:       "height": 419328
Jul 21 22:16:55 myNode lnd[22333]:       "active": true,
Jul 21 22:16:55 myNode lnd[22333]:       "type": "buried",
Jul 21 22:16:55 myNode lnd[22333]:     "csv": {
Jul 21 22:16:55 myNode lnd[22333]:     },
Jul 21 22:16:55 myNode lnd[22333]:       "height": 388381
Jul 21 22:16:55 myNode lnd[22333]:       "active": true,
Jul 21 22:16:55 myNode lnd[22333]:       "type": "buried",
Jul 21 22:16:55 myNode lnd[22333]:     "bip65": {
Jul 21 22:16:55 myNode lnd[22333]:     },
Jul 21 22:16:55 myNode lnd[22333]:       "height": 363725
Jul 21 22:16:55 myNode lnd[22333]:       "active": true,
Jul 21 22:16:55 myNode lnd[22333]:       "type": "buried",
Jul 21 22:16:55 myNode lnd[22333]:     "bip66": {
Jul 21 22:16:55 myNode lnd[22333]:     },
Jul 21 22:16:55 myNode lnd[22333]:       "height": 227931
Jul 21 22:16:55 myNode lnd[22333]:       "active": true,
Jul 21 22:16:55 myNode lnd[22333]:       "type": "buried",
Jul 21 22:16:55 myNode lnd[22333]:     "bip34": {
Jul 21 22:16:55 myNode lnd[22333]:   "softforks": {
Jul 21 22:16:55 myNode lnd[22333]:   "pruned": false,
Jul 21 22:16:55 myNode lnd[22333]:   "size_on_disk": 328221488089,
Jul 21 22:16:55 myNode lnd[22333]:   "chainwork": "00000000000000000000000000000000000000001193a2e4d5960ab9e1153a46",
Jul 21 22:16:55 myNode lnd[22333]:   "initialblockdownload": false,
Jul 21 22:16:55 myNode lnd[22333]:   "verificationprogress": 0.9999922818012293,
Jul 21 22:16:55 myNode lnd[22333]:   "mediantime": 1595384395,
Jul 21 22:16:55 myNode lnd[22333]:   "difficulty": 17345948872516.06,
Jul 21 22:16:55 myNode lnd[22333]:   "bestblockhash": "00000000000000000000c485f9cea96d341ab9fa74134990a989d11a6c88f67b",
Jul 21 22:16:55 myNode lnd[22333]:   "headers": 640225,
Jul 21 22:16:55 myNode lnd[22333]:   "blocks": 640225,
Jul 21 22:16:55 myNode lnd[22333]:   "chain": "main",
Jul 21 22:16:55 myNode lnd[22333]: {
Jul 21 22:16:55 myNode lnd[22333]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
Jul 21 22:16:55 myNode lnd[22333]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoind_synced ']'
Jul 21 22:16:55 myNode lnd[22333]: Checking if Bitcoin is synced...
```

**Comment by tehelsper** [comment]
Unfortunately, that looks like there was corruption in the lnd database files. You will likely need to restore your wallet.

**Comment by asperks** [comment]
Backed up channel.backup again.  Deleted wallet.  Restored from seed.  Now says that it's syncing.  Will see how it goes.

**Comment by asperks** [comment]
Deleted wallet.  Restored from seed.  Used restore channel.backup and restored the open channels.  Sent them to another address.  What wasn't there was the on-chain funds of the wallet, and no matter what I do, I couldn't see them with the node.  But this doesn't have anything to do with mynode.   I know that I'll be able to use the seed to generate the private addresses if I need to and retrieve those funds.

The rest of this isn't a mynode problem.  So I'll close this one out.
