### ISSUE TITLE
Specter wallet not starting after upgrade to 0.2.32

### ISSUE THREAD

**Issue by danilotg** [mynodebtc/mynode#536]
Restart and Uninstall didn't help to fix the issue:

-- Logs begin at Mon 2021-05-17 09:19:14 CDT, end at Mon 2021-05-17 09:43:17 CDT. --
May 17 09:43:07 myNode systemd[1]: specter.service: Failed with result 'exit-code'.
May 17 09:43:07 myNode systemd[1]: specter.service: Main process exited, code=exited, status=1/FAILURE
May 17 09:43:07 myNode specter[10744]: [Errno 111] Connection refused
May 17 09:43:07 myNode specter[10744]: Initializing HWI...
May 17 09:43:07 myNode specter[10744]: cryptoadvance.specter.specter_error.SpecterError: Unable to parse user JSON.
May 17 09:43:07 myNode specter[10744]:     raise SpecterError("Unable to parse user JSON.")
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/user.py", line 78, in from_json
May 17 09:43:07 myNode specter[10744]:     self.users = [User.from_json(u, self.specter) for u in users]
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/user_manager.py", line 41, in 
May 17 09:43:07 myNode specter[10744]:     self.users = [User.from_json(u, self.specter) for u in users]
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/user_manager.py", line 41, in load_users
May 17 09:43:07 myNode specter[10744]:     self.load_users()
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/user_manager.py", line 46, in update
May 17 09:43:07 myNode specter[10744]:     self.update()
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/user_manager.py", line 20, in __init__
May 17 09:43:07 myNode specter[10744]:     self.user_manager = UserManager(self)
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/specter.py", line 117, in __init__
May 17 09:43:07 myNode specter[10744]:     config=app.config["DEFAULT_SPECTER_CONFIG"],
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/server.py", line 87, in init_app
May 17 09:43:07 myNode specter[10744]:     init_app(app, hwibridge=hwibridge)
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/cli/cli_server.py", line 138, in server
May 17 09:43:07 myNode specter[10744]:     return callback(*args, **kwargs)
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
May 17 09:43:07 myNode specter[10744]:     return ctx.invoke(self.callback, **ctx.params)
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
May 17 09:43:07 myNode specter[10744]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
May 17 09:43:07 myNode specter[10744]:     rv = self.invoke(ctx)
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/click/core.py", line 782, in main
May 17 09:43:07 myNode specter[10744]:     return self.main(*args, **kwargs)
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
May 17 09:43:07 myNode specter[10744]:     entry_point()
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/__main__.py", line 19, in 
May 17 09:43:07 myNode specter[10744]:     exec(code, run_globals)
May 17 09:43:07 myNode specter[10744]:   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
May 17 09:43:07 myNode specter[10744]:     "__main__", mod_spec)
May 17 09:43:07 myNode specter[10744]:   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
May 17 09:43:07 myNode specter[10744]: Traceback (most recent call last):
May 17 09:43:07 myNode specter[10744]: During handling of the above exception, another exception occurred:
May 17 09:43:07 myNode specter[10744]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
May 17 09:43:07 myNode specter[10744]:     raise JSONDecodeError("Expecting value", s, err.value) from None
May 17 09:43:07 myNode specter[10744]:   File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
May 17 09:43:07 myNode specter[10744]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
May 17 09:43:07 myNode specter[10744]:   File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
May 17 09:43:07 myNode specter[10744]:     return _default_decoder.decode(s)
May 17 09:43:07 myNode specter[10744]:   File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
May 17 09:43:07 myNode specter[10744]:     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
May 17 09:43:07 myNode specter[10744]:   File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load
May 17 09:43:07 myNode specter[10744]:     content = json.load(f)
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/persistence.py", line 29, in read_json_file
May 17 09:43:07 myNode specter[10744]:     raise e
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/persistence.py", line 34, in read_json_file
May 17 09:43:07 myNode specter[10744]:     self.data = read_json_file(self.data_file)
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/managers/genericdata_manager.py", line 27, in load
May 17 09:43:07 myNode specter[10744]:     self.load()
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/managers/genericdata_manager.py", line 18, in __init__
May 17 09:43:07 myNode specter[10744]:     super().__init__(data_folder)
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/managers/config_manager.py", line 31, in __init__
May 17 09:43:07 myNode specter[10744]:     self._config_manager = ConfigManager(self.data_folder)
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/specter.py", line 752, in config_manager
May 17 09:43:07 myNode specter[10744]:     return self.config_manager.data
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/specter.py", line 265, in config
May 17 09:43:07 myNode specter[10744]:     self.uid = specter.config["uid"]
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/user.py", line 44, in __init__
May 17 09:43:07 myNode specter[10744]:     is_admin=True,
May 17 09:43:07 myNode specter[10744]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/user.py", line 75, in from_json
May 17 09:43:07 myNode specter[10744]: Traceback (most recent call last):
May 17 09:43:07 myNode specter[10744]: [2021-05-17 09:43:07,181] INFO in server: Initializing Specter

**Comment by tehelsper** [comment]
Could you email support with you the contents of your config file?

You can see it with the following command:

sudo cat /mnt/hdd/mynode/specter/config.json
