### ISSUE TITLE
VPN info crashes with error

### ISSUE THREAD

**Issue by bloodir** [mynodebtc/mynode#567]
Anytime I try to go to VPN info section myNode just gives me error, tested on two nodes with latest version. Same result. Both are on the same network.

<a href="https://ibb.co/hyHrjbN"><img src="https://i.ibb.co/qd9hfK8/vpn-error.png" alt="vpn-error" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>upload pic</a><br />

 - Firefox latest, Linux Mint OS 18.3
 - myNode 0.2.42 64bit
 - Raspi 4 8gb

Error from the weblog:

```
OSError: [Errno 2] No such file or directory
Sep 24 13:27:51 myNode www[701]:     raise child_exception
Sep 24 13:27:51 myNode www[701]:   File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
Sep 24 13:27:51 myNode www[701]:     errread, errwrite)
Sep 24 13:27:51 myNode www[701]:   File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
Sep 24 13:27:51 myNode www[701]:     return Popen(*popenargs, **kwargs).wait()
Sep 24 13:27:51 myNode www[701]:   File "/usr/lib/python2.7/subprocess.py", line 172, in call
Sep 24 13:27:51 myNode www[701]:     if subprocess.call(["nc", "-v", "-u", "-w", "1", ip, "51194"]) == 0:
Sep 24 13:27:51 myNode www[701]:   File "/var/www/mynode/vpn.py", line 28, in page_vpn_info
Sep 24 13:27:51 myNode www[701]:     return self.view_functions[rule.endpoint](**req.view_args)
Sep 24 13:27:51 myNode www[701]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1936, in dispatch_request
Sep 24 13:27:51 myNode www[701]:     rv = self.dispatch_request()
Sep 24 13:27:51 myNode www[701]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
Sep 24 13:27:51 myNode www[701]:     reraise(exc_type, exc_value, tb)
Sep 24 13:27:51 myNode www[701]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
Sep 24 13:27:51 myNode www[701]:     rv = self.handle_user_exception(e)
Sep 24 13:27:51 myNode www[701]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
Sep 24 13:27:51 myNode www[701]:     response = self.full_dispatch_request()
Sep 24 13:27:51 myNode www[701]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2447, in wsgi_app
Sep 24 13:27:51 myNode www[701]: Traceback (most recent call last):
Sep 24 13:27:51 myNode www[701]: [2021-09-24 13:27:51,876] ERROR in app: Exception on /vpn-info [GET]
```

**Comment by tehelsper** [comment]
Could you try running this command to see if it succeeds? It looks like that command may be failing.

nc -v -u -w 1 <your IP address> 51194

**Comment by bloodir** [comment]
Command not found, also not in packages, what is nc?

**Comment by tehelsper** [comment]
Yeah, looks like it was missed on RP4 64-bit. It will be fixed next upgrade.

Also, sorry, the formatting got screwed up in my last message and missed the IP. Try this:

nc -v -u -w 1 DEVICE_IP_ADDRESS 51194

**Comment by bloodir** [comment]
This new command showed me:
Warning: _forward host lookup failed for ip_

and _ip (?) open_

I guess that means port is open, but not sure what is forward host lookup.

**Comment by tehelsper** [comment]
I think that version of netcat may be different. Try after the next upgrade or try running this:

sudo apt-get install netcat-openbsd

**Comment by bloodir** [comment]
Nice, now it worked!
