### ISSUE TITLE
BTCpayServer issue with NBXplorer

### ISSUE THREAD

**Issue by zbajor1** [mynodebtc/mynode#659]
I have a problem with btcpayserver 

BTC

    The node is offline
    Last error: Name or service not known (nbxplorer:32838)

 After fresh install and full sync +btcpay enabled i got that error on btcpay start page,
i am running latest 0.2.55 mynodebtc and TCPay Server v1.5.1.0 on VM

after inspection i  found error in docker container nicolasdorier/nbxplorer:2.3.16 (this container restart every few sec )

info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: Configuration:  Network: Mainnet
Unhandled exception. System.FormatException: Invalid RPC Credential string
   at NBitcoin.RPC.RPCCredentialString.Parse(String str)
   at NBitcoin.RPC.RPCClient..ctor(String authenticationString, Uri address, Network network)
   at NBitcoin.RPC.RPCClient..ctor(NetworkCredential credentials, Uri address, Network network)
   at NBXplorer.Configuration.RPCArgs.ConfigureRPCClient(NBXplorerNetwork networkInformation) in /source/NBXplorer/Configuration/RPCArgs.cs:line 54
   at NBXplorer.Configuration.ExplorerConfiguration.LoadArgs(IConfiguration config) in /source/NBXplorer/Configuration/ExplorerConfiguration.cs:line 138
   at NBXplorer.Program.Main(String[] args) in /source/NBXplorer/Program.cs:line 40

seems like RPC credentials are issue here

i dont know how to fix it, i had no problems with mynodebtc before

is there anyone who can help here ?

Best Regrads

**Comment by tehelsper** [comment]
Try a re-install of BTC Pay Server after upgrading. In the most recent release the install process of BTC Pay has been totally revamped. Also, the next release will have another BTC Pay update.
