### ISSUE TITLE
panic: freepages: failed to get all reachable pages

### ISSUE THREAD

**Issue by HamishMacEwan** [mynodebtc/mynode#686]
**Describe the bug**
After a failed disk clone (power issues with the new SSD I suspect), rebooted and had this problem.  I understand from other reports here and elsewhere that the only solution is to reset and restore the wallet. C'est la vie.

However, I'm wondering how the source drive (a 1TB HDD) became corrupted.  It might have been part of the issue that caused the problem for the SSD, but it might be something else.  

Just a heads up.

**Expected behavior**
That if the clone failed, the original drive would be unchanged and it would be possible to reboot with it in place.  This was correct with respect to everything else, but `lnd` won't come back

**MyNode hardware (please complete the following information):**
 - Device: Raspi400
 - Version 0.2.57

**Additional context**
```
Jul 27 18:59:23 flat6 lnd[30574]: 2022-07-27 18:59:23.335 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 27 18:59:23 flat6 lnd[30574]: 2022-07-27 18:59:23.335 [INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=true
Jul 27 18:59:23 flat6 lnd[30574]: 2022-07-27 18:59:23.336 [INF] CHDB: Not compacting database file at /home/bitcoin/.lnd/data/graph/mainnet/channel.db, it was last compacted at 2022-07-24 18:36:34.498991318 +1200 NZST (72h22m48s ago), min age is set to 168h0m0s
Jul 27 18:59:24 flat6 lnd[30574]: panic: freepages: failed to get all reachable pages (page 8159: multiple references)
Jul 27 18:59:24 flat6 lnd[30574]: goroutine 185 [running]:
Jul 27 18:59:24 flat6 lnd[30574]: go.etcd.io/bbolt.(*DB).freepages.func2(0x40006feea0)
Jul 27 18:59:24 flat6 lnd[30574]:         go.etcd.io/bbolt@v1.3.6/db.go:1056 +0xc4
Jul 27 18:59:24 flat6 lnd[30574]: created by go.etcd.io/bbolt.(*DB).freepages
Jul 27 18:59:24 flat6 lnd[30574]:         go.etcd.io/bbolt@v1.3.6/db.go:1054 +0x134
Jul 27 18:59:24 flat6 systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 27 18:59:33 flat6 systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 27 18:59:33 flat6 systemd[1]: Failed to start LND Lightning Daemon.
```

**Comment by tehelsper** [comment]
When cloning, the original drive should not be modified at all, but a raspberry pi cannot really power two drives. If I had to guess, it either happened before the clone or a power issue caused it by trying to power two devices. When cloning, I tend to power both drives via a powered USB hub.
