### ISSUE TITLE
LND node becomes unreachable

### ISSUE THREAD

**Issue by rico2095** [mynodebtc/mynode#693]
My lightning Node becomes unreachable for about 10 -20 a few times a day, i have lndg uninstalled as someone suggested this could be the problem.  I currently have 2 channels open and use Tor.
any Ideas?
 Thanks

**Comment by tehelsper** [comment]
Are you accessing the UI via tor? If so, tor can be intermittent. When it goes down, can you check the uptime on the status page to see if it rebooted?

**Comment by rico2095** [comment]
I'm using bolt observer and I just getting notifications few times a day saving it's unreachable, normally for about 15 mins at a time. 
The uptime on settings page is for over 7 days

**Comment by tehelsper** [comment]
Gotcha, in that case I would expect tor to be the issue. If you could happen to catch the LND logs while it's down that could rule out any actual Lightning issues.

**Comment by rico2095** [comment]
here are some logs:

-- Logs begin at Sun 2022-08-28 05:58:34 CDT, end at Tue 2022-08-30 04:43:45 CDT. --
Aug 30 04:43:21 myNode lndhub[26780]: LND not synced, sleeping for 60 seconds...
Aug 30 04:43:21 myNode lndhub[26780]: [lncli] rpc error: code = Unknown desc = waiting to start, RPC services not available
Aug 30 04:42:21 myNode lndhub[26780]: LND not synced, sleeping for 60 seconds...
Aug 30 04:42:21 myNode lndhub[26780]: [lncli] rpc error: code = Unknown desc = waiting to start, RPC services not available
Aug 30 04:42:21 myNode lndhub[26780]: Checking if LND is synced...
Aug 30 04:42:20 myNode lndhub[26719]: Not shutting down!
Aug 30 04:42:20 myNode lndhub[26719]: Checking if device is shutting down...
Aug 30 04:42:20 myNode systemd[1]: Starting LND Hub...
Aug 30 04:42:20 myNode systemd[1]: Stopped LND Hub.
Aug 30 04:42:20 myNode systemd[1]: lndhub.service: Scheduled restart job, restart counter is at 57.
Aug 30 04:42:20 myNode systemd[1]: lndhub.service: Service RestartSec=1min expired, scheduling restart.
Aug 30 04:41:20 myNode systemd[1]: Failed to start LND Hub.
Aug 30 04:41:20 myNode systemd[1]: lndhub.service: Failed with result 'timeout'.
Aug 30 04:41:20 myNode systemd[1]: lndhub.service: Control process exited, code=killed, status=15/TERM
Aug 30 04:41:20 myNode systemd[1]: lndhub.service: Start-pre operation timed out. Terminating.
Aug 30 04:40:21 myNode lndhub[25886]: LND not synced, sleeping for 60 seconds...
Aug 30 04:40:21 myNode lndhub[25886]: [lncli] rpc error: code = Unknown desc = waiting to start, RPC services not available
Aug 30 04:39:21 myNode lndhub[25886]: LND not synced, sleeping for 60 seconds...
Aug 30 04:39:21 myNode lndhub[25886]: [lncli] rpc error: code = Unknown desc = waiting to start, RPC services not available
Aug 30 04:38:21 myNode lndhub[25886]: LND not synced, sleeping for 60 seconds...
Aug 30 04:38:21 myNode lndhub[25886]: [lncli] rpc error: code = Unknown desc = waiting to start, RPC services not available
Aug 30 04:37:20 myNode lndhub[25886]: LND not synced, sleeping for 60 seconds...
Aug 30 04:37:20 myNode lndhub[25886]: [lncli] rpc error: code = Unknown desc = waiting to start, RPC services not available
Aug 30 04:37:20 myNode lndhub[25886]: Checking if LND is synced...
Aug 30 04:37:20 myNode lndhub[25839]: Not shutting down!
Aug 30 04:37:20 myNode lndhub[25839]: Checking if device is shutting down...
Aug 30 04:37:20 myNode systemd[1]: Starting LND Hub...
Aug 30 04:35:16 myNode systemd[1]: Stopped LND Hub.
Aug 30 04:35:16 myNode systemd[1]: lndhub.service: Scheduled restart job, restart counter is at 56.
Aug 30 04:35:16 myNode systemd[1]: lndhub.service: Service RestartSec=1min expired, scheduling restart.
Aug 30 04:34:15 myNode systemd[1]: Failed to start LND Hub.
Aug 30 04:34:15 myNode systemd[1]: lndhub.service: Failed with result 'timeout'.
Aug 30 04:34:15 myNode systemd[1]: lndhub.service: Control process exited, code=killed, status=15/TERM
Aug 30 04:34:15 myNode systemd[1]: lndhub.service: Start-pre operation timed out. Terminating.
Aug 30 04:33:16 myNode lndhub[24691]: LND not synced, sleeping for 60 seconds...
Aug 30 04:33:16 myNode lndhub[24691]: [lncli] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"
Aug 30 04:32:16 myNode lndhub[24691]: LND not synced, sleeping for 60 seconds...
Aug 30 04:32:16 myNode lndhub[24691]: [lncli] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"
Aug 30 04:31:16 myNode lndhub[24691]: LND not synced, sleeping for 60 seconds...
Aug 30 04:31:16 myNode lndhub[24691]: [lncli] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"
Aug 30 04:30:16 myNode lndhub[24691]: LND not synced, sleeping for 60 seconds...
Aug 30 04:30:16 myNode lndhub[24691]: [lncli] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"
Aug 30 04:30:15 myNode lndhub[24691]: Checking if LND is synced...
Aug 30 04:30:15 myNode lndhub[24636]: Not shutting down!
Aug 30 04:30:15 myNode lndhub[24636]: Checking if device is shutting down...
Aug 30 04:30:15 myNode systemd[1]: Starting LND Hub...
Aug 30 04:27:14 myNode systemd[1]: Stopped LND Hub.
Aug 30 04:27:14 myNode systemd[1]: lndhub.service: Scheduled restart job, restart counter is at 55.
Aug 30 04:27:14 myNode systemd[1]: lndhub.service: Service RestartSec=1min expired, scheduling restart.
Aug 30 04:26:14 myNode systemd[1]: lndhub.service: Failed with result 'exit-code'.
Aug 30 04:26:14 myNode systemd[1]: lndhub.service: Main process exited, code=exited, status=4/NOPERMISSION
Aug 30 04:26:13 myNode lndhub[445]: }
Aug 30 04:26:13 myNode lndhub[445]:   metadata: Metadata { internalRepr: Map(0) {}, options: {} }
Aug 30 04:26:13 myNode lndhub[445]:   details: 'Connection dropped',
Aug 30 04:26:13 myNode lndhub[445]:   code: 14,
Aug 30 04:26:13 myNode lndhub[445]:     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
Aug 30 04:26:13 myNode lndhub[445]:     at /opt/mynode/LndHub/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
Aug 30 04:26:13 myNode lndhub[445]:     at Object.onReceiveStatus (/opt/mynode/LndHub/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
Aug 30 04:26:13 myNode lndhub[445]:     at Object.onReceiveStatus (/opt/mynode/LndHub/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
Aug 30 04:26:13 myNode lndhub[445]:     at Object.onReceiveStatus (/opt/mynode/LndHub/node_modules/@grpc/grpc-js/src/client.ts:338:36)
Aug 30 04:26:13 myNode lndhub[445]:     at Object.callErrorFromStatus (/opt/mynode/LndHub/node_modules/@grpc/grpc-js/src/call.ts:81:24)
Aug 30 04:26:13 myNode lndhub[445]: lnd failure: Error: 14 UNAVAILABLE: Connection dropped
Aug 30 04:25:50 myNode lndhub[445]: updated

Aug 30 04:38:42 myNode lnd[25818]: 2022-08-30 04:38:42.924 [ERR] RPCS: [/lnrpc.Lightning/ChannelBalance]: waiting to start, RPC services not available
Aug 30 04:38:42 myNode lnd[25818]: 2022-08-30 04:38:42.880 [ERR] RPCS: [/lnrpc.Lightning/ListChannels]: waiting to start, RPC services not available
Aug 30 04:38:42 myNode lnd[25818]: 2022-08-30 04:38:42.835 [ERR] RPCS: [/lnrpc.Lightning/ListPeers]: waiting to start, RPC services not available
Aug 30 04:38:42 myNode lnd[25818]: 2022-08-30 04:38:42.780 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
Aug 30 04:38:21 myNode lnd[25818]: 2022-08-30 04:38:21.048 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
Aug 30 04:38:21 myNode lnd[25818]: 2022-08-30 04:38:21.039 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
Aug 30 04:38:21 myNode lnd[25818]: 2022-08-30 04:38:21.030 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
Aug 30 04:37:42 myNode lnd[25818]: 2022-08-30 04:37:42.699 [ERR] RPCS: [/lnrpc.Lightning/ListInvoices]: waiting to start, RPC services not available
Aug 30 04:37:42 myNode lnd[25818]: 2022-08-30 04:37:42.664 [ERR] RPCS: [/lnrpc.Lightning/ListPayments]: waiting to start, RPC services not available
Aug 30 04:37:42 myNode lnd[25818]: 2022-08-30 04:37:42.631 [ERR] RPCS: [/lnrpc.Lightning/GetTransactions]: waiting to start, RPC services not available
Aug 30 04:37:42 myNode lnd[25818]: 2022-08-30 04:37:42.597 [ERR] RPCS: [/wtclientrpc.WatchtowerClient/Policy]: waiting to start, RPC services not available
Aug 30 04:37:42 myNode lnd[25818]: 2022-08-30 04:37:42.559 [ERR] RPCS: [/wtclientrpc.WatchtowerClient/Stats]: waiting to start, RPC services not available
Aug 30 04:37:42 myNode lnd[25818]: 2022-08-30 04:37:42.522 [ERR] RPCS: [/wtclientrpc.WatchtowerClient/ListTowers]: waiting to start, RPC services not available
Aug 30 04:37:42 myNode lnd[25818]: 2022-08-30 04:37:42.487 [ERR] RPCS: [/watchtowerrpc.Watchtower/GetInfo]: waiting to start, RPC services not available
Aug 30 04:37:42 myNode lnd[25818]: 2022-08-30 04:37:42.432 [ERR] RPCS: [/lnrpc.Lightning/WalletBalance]: waiting to start, RPC services not available
Aug 30 04:37:42 myNode lnd[25818]: 2022-08-30 04:37:42.397 [ERR] RPCS: [/lnrpc.Lightning/ChannelBalance]: waiting to start, RPC services not available
Aug 30 04:37:42 myNode lnd[25818]: 2022-08-30 04:37:42.365 [ERR] RPCS: [/lnrpc.Lightning/ListChannels]: waiting to start, RPC services not available
Aug 30 04:37:42 myNode lnd[25818]: 2022-08-30 04:37:42.330 [ERR] RPCS: [/lnrpc.Lightning/ListPeers]: waiting to start, RPC services not available
Aug 30 04:37:42 myNode lnd[25818]: 2022-08-30 04:37:42.295 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
Aug 30 04:37:20 myNode lnd[25818]: 2022-08-30 04:37:20.886 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
Aug 30 04:37:20 myNode lnd[25818]: 2022-08-30 04:37:20.875 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
Aug 30 04:37:20 myNode lnd[25818]: 2022-08-30 04:37:20.875 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
Aug 30 04:37:20 myNode systemd[1]: Started LND Lightning Daemon.
Aug 30 04:37:12 myNode lnd[25818]: 2022-08-30 04:37:12.447 [INF] CHDB: Not compacting database file at /home/bitcoin/.lnd/data/graph/mainnet/channel.db, it was last compacted at 2022-08-24 04:50:29.956137924 -0500 CDT (143h46m42s ago), min age is set to 168h0m0s
Aug 30 04:37:12 myNode lnd[25818]: 2022-08-30 04:37:12.182 [INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=true
Aug 30 04:37:12 myNode lnd[25818]: 2022-08-30 04:37:12.182 [INF] LTND: Opening the main database, this might take a few minutes...
Aug 30 04:37:12 myNode lnd[25818]: 2022-08-30 04:37:12.182 [INF] RPCS: gRPC proxy started at 0.0.0.0:10080
Aug 30 04:37:12 myNode lnd[25818]: 2022-08-30 04:37:12.140 [INF] RPCS: RPC server listening on 0.0.0.0:10009
Aug 30 04:37:11 myNode lnd[25818]: 2022-08-30 04:37:11.624 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Aug 30 04:37:11 myNode lnd[25818]: 2022-08-30 04:37:11.623 [INF] LTND: Version: 0.15.0-beta commit=v0.15.0-beta, build=production, logging=default, debuglevel=info
Aug 30 04:37:10 myNode lnd[25818]: Automatically obtained bitcoind's RPC credentials
Aug 30 04:37:10 myNode lnd[25818]: Attempting automatic RPC configuration to bitcoind
Aug 30 04:37:09 myNode lnd[25379]: + exit 0
Aug 30 04:37:09 myNode lnd[25379]: }
Aug 30 04:37:09 myNode lnd[25379]:   "warnings": ""
Aug 30 04:37:09 myNode lnd[25379]:   "pruned": false,
Aug 30 04:37:09 myNode lnd[25379]:   "size_on_disk": 482274076622,
Aug 30 04:37:09 myNode lnd[25379]:   "chainwork": "0000000000000000000000000000000000000000341fb8afec7e571197efffca",
Aug 30 04:37:09 myNode lnd[25379]:   "initialblockdownload": false,
Aug 30 04:37:09 myNode lnd[25379]:   "verificationprogress": 0.9999968525600771,
Aug 30 04:37:09 myNode lnd[25379]:   "mediantime": 1661848623,
Aug 30 04:37:09 myNode lnd[25379]:   "time": 1661851401,
Aug 30 04:37:09 myNode lnd[25379]:   "difficulty": 28351606743493.77,
Aug 30 04:37:09 myNode lnd[25379]:   "bestblockhash": "000000000000000000068465253454e9186aa3c75cb8a1fb18c0ea3aa6ed01cc",
Aug 30 04:37:09 myNode lnd[25379]:   "headers": 751833,
Aug 30 04:37:09 myNode lnd[25379]:   "blocks": 751833,

**Comment by rico2095** [comment]
Any ideas??

**Comment by tehelsper** [comment]
It looks like lnd is having trouble starting for some reason, but I don't see any specific errors. Do the waiting to start messages ever go away?

**Comment by rico2095** [comment]
Yes it works as normal but goes offline around 4 times a day

**Comment by tehelsper** [comment]
I'm not sure. What happened right before the beginning of that log? Can you tell if LND is restarting?

**Comment by rico2095** [comment]
I'm not sure

**Comment by rico2095** [comment]
On the main page the peers go to zero, then it seems to back again with peers back to around 5/6

Many Thanks
Mark

**Comment by tehelsper** [comment]
LND may be down now due to a bug. Try upgrading to the latest version of MyNode.

**Comment by rico2095** [comment]
Have upgraded to latest version and still comes unreachable 4/5 times a day

**Comment by rico2095** [comment]
Looks like latest update has fixed the issue :)

**Comment by rico2095** [comment]
Seems to be coming unreachable about 6 times a day now... please help

**Comment by tehelsper** [comment]
Tips
- Make sure LND is running the latest version v0.15.4
- Check if LND is actually restarting, you would need to watch the logs
- Don't use tor, it can be flakey if you are monitoring via an external service
