### ISSUE TITLE
Electrum Server sync stuck at 99.9X%

### ISSUE THREAD

**Issue by bucadoX** [mynodebtc/mynode#721]
Since a week or so electrums doesn't sync to 100% anymore. No updates were installed in the meantime. I reset the database, regenerated the certificates and put the bitcoind config back to default, but no change other than the syncing gets stuck at slightly different %.

Logs below:

```
-- Logs begin at Sat 2022-11-05 03:02:44 CDT, end at Sat 2022-11-05 06:44:02 CDT. --
Nov 05 06:43:08 myNode systemd[1]: electrs.service: Failed with result 'exit-code'.
Nov 05 06:43:08 myNode systemd[1]: electrs.service: Main process exited, code=exited, status=1/FAILURE
Nov 05 06:43:08 myNode electrs[23725]:     2: receiving on an empty and disconnected channel
Nov 05 06:43:08 myNode electrs[23725]:     1: failed to get block 000000000000000000070742427fa10ec3c66d006160155a704d9f56d090a3ea
Nov 05 06:43:08 myNode electrs[23725]:     0: sync failed
Nov 05 06:43:08 myNode electrs[23725]: Caused by:
Nov 05 06:43:08 myNode electrs[23725]: Error: electrs failed
Nov 05 06:43:08 myNode electrs[23725]: [2022-11-05T11:43:08.216Z INFO  electrs::db] closing DB at /mnt/hdd/mynode/electrs/bitcoin
Nov 05 06:43:08 myNode electrs[23725]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 05 06:43:08 myNode electrs[23725]: thread 'p2p_recv' panicked at 'invalid message: OversizedVectorAllocation { requested: 12000072, max: 4000000 }', src/p2p.rs:211:62
Nov 05 06:43:07 myNode electrs[23725]: [2022-11-05T11:43:07.994Z INFO  electrs::index] indexing 581 blocks: [761241..761821]
Nov 05 06:43:07 myNode electrs[23725]: [2022-11-05T11:43:07.951Z INFO  electrs::chain] chain updated: tip=000000000000000000022fa13b5abb217c073ed005a73834cb886470af426678, height=761240
Nov 05 06:43:03 myNode electrs[23725]: [2022-11-05T11:43:03.142Z INFO  electrs::chain] loading 761240 headers, tip=000000000000000000022fa13b5abb217c073ed005a73834cb886470af426678
Nov 05 06:42:58 myNode electrs[23725]: [2022-11-05T11:42:58.524Z INFO  electrs::db] "/mnt/hdd/mynode/electrs/bitcoin": 1051 SST files, 56.664232152 GB, 4.696112756 Grows
Nov 05 06:42:58 myNode electrs[23725]: [2022-11-05T11:42:58.244Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
Nov 05 06:42:58 myNode electrs[23725]: [2022-11-05T11:42:58.244Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
Nov 05 06:42:58 myNode electrs[23725]: Starting electrs 0.9.3 on aarch64 linux with Config { network: Bitcoin, db_path: "/mnt/hdd/mynode/electrs/bitcoin", daemon_dir: "/home/bitcoin/.bitcoin", daemon_auth: CookieFile("/home/bitcoin/.bitcoin/.cookie"), daemon_rpc_addr: 127.0.0.1:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 15s, jsonrpc_timeout: 30s, index_batch_size: 10, index_lookup_limit: Some(200), reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.9.3 (Electrum Rust Server)!", args: [] }
Nov 05 06:42:58 myNode systemd[1]: Started myNode Electrum Server.
Nov 05 06:42:58 myNode electrs[23723]: + exit 0
Nov 05 06:42:58 myNode electrs[23723]: }
Nov 05 06:42:58 myNode electrs[23723]:   "warnings": ""
Nov 05 06:42:58 myNode electrs[23723]:   },
Nov 05 06:42:58 myNode electrs[23723]:     }
Nov 05 06:42:58 myNode electrs[23723]:       "active": true
Nov 05 06:42:58 myNode electrs[23723]:       "height": 709632,
Nov 05 06:42:58 myNode electrs[23723]:       },
Nov 05 06:42:58 myNode electrs[23723]:         "min_activation_height": 709632
Nov 05 06:42:58 myNode electrs[23723]:         "since": 709632,
Nov 05 06:42:58 myNode electrs[23723]:         "timeout": 1628640000,
Nov 05 06:42:58 myNode electrs[23723]:         "start_time": 1619222400,
Nov 05 06:42:58 myNode electrs[23723]:         "status": "active",
Nov 05 06:42:58 myNode electrs[23723]:       "bip9": {
Nov 05 06:42:58 myNode electrs[23723]:       "type": "bip9",
Nov 05 06:42:58 myNode electrs[23723]:     "taproot": {
Nov 05 06:42:58 myNode electrs[23723]:     },
Nov 05 06:42:58 myNode electrs[23723]:       "height": 481824
Nov 05 06:42:58 myNode electrs[23723]:       "active": true,
Nov 05 06:42:58 myNode electrs[23723]:       "type": "buried",
Nov 05 06:42:58 myNode electrs[23723]:     "segwit": {
Nov 05 06:42:58 myNode electrs[23723]:     },
Nov 05 06:42:58 myNode electrs[23723]:       "height": 419328
Nov 05 06:42:58 myNode electrs[23723]:       "active": true,
Nov 05 06:42:58 myNode electrs[23723]:       "type": "buried",
Nov 05 06:42:58 myNode electrs[23723]:     "csv": {
Nov 05 06:42:58 myNode electrs[23723]:     },
Nov 05 06:42:58 myNode electrs[23723]:       "height": 388381
Nov 05 06:42:58 myNode electrs[23723]:       "active": true,
Nov 05 06:42:58 myNode electrs[23723]:       "type": "buried",
Nov 05 06:42:58 myNode electrs[23723]:     "bip65": {
Nov 05 06:42:58 myNode electrs[23723]:     },
Nov 05 06:42:58 myNode electrs[23723]:       "height": 363725
Nov 05 06:42:58 myNode electrs[23723]:       "active": true,
Nov 05 06:42:58 myNode electrs[23723]:       "type": "buried",
Nov 05 06:42:58 myNode electrs[23723]:     "bip66": {
Nov 05 06:42:58 myNode electrs[23723]:     },
Nov 05 06:42:58 myNode electrs[23723]:       "height": 227931
Nov 05 06:42:58 myNode electrs[23723]:       "active": true,
Nov 05 06:42:58 myNode electrs[23723]:       "type": "buried",
Nov 05 06:42:58 myNode electrs[23723]:     "bip34": {
Nov 05 06:42:58 myNode electrs[23723]:   "softforks": {
Nov 05 06:42:58 myNode electrs[23723]:   "pruned": false,
Nov 05 06:42:58 myNode electrs[23723]:   "size_on_disk": 495654260974,
Nov 05 06:42:58 myNode electrs[23723]:   "chainwork": "000000000000000000000000000000000000000038ba89cfce49d11513aca6c2",
Nov 05 06:42:58 myNode electrs[23723]:   "initialblockdownload": false,
Nov 05 06:42:58 myNode electrs[23723]:   "verificationprogress": 0.9999964274784583,
Nov 05 06:42:58 myNode electrs[23723]:   "mediantime": 1667643988,
Nov 05 06:42:58 myNode electrs[23723]:   "difficulty": 36835682546787.98,
Nov 05 06:42:58 myNode electrs[23723]:   "bestblockhash": "00000000000000000000dd0d11630a583a7f7c16f5157bcc0910dfa70fedc689",
Nov 05 06:42:58 myNode electrs[23723]:   "headers": 761821,
Nov 05 06:42:58 myNode electrs[23723]:   "blocks": 761821,
Nov 05 06:42:58 myNode electrs[23723]:   "chain": "main",
Nov 05 06:42:58 myNode electrs[23723]: {
Nov 05 06:42:58 myNode electrs[23723]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
Nov 05 06:42:58 myNode electrs[23723]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoin_synced ']'
Nov 05 06:42:58 myNode electrs[23723]: Checking if Bitcoin is synced...
Nov 05 06:42:58 myNode electrs[23723]: + echo 'Checking if Bitcoin is synced...'
Nov 05 06:42:58 myNode electrs[23723]: + set -e
Nov 05 06:42:58 myNode electrs[23722]: Not shutting down!
Nov 05 06:42:58 myNode electrs[23722]: Checking if device is shutting down...
Nov 05 06:42:58 myNode systemd[1]: Starting myNode Electrum Server...
Nov 05 06:42:58 myNode systemd[1]: Stopped myNode Electrum Server.
Nov 05 06:42:58 myNode systemd[1]: electrs.service: Scheduled restart job, restart counter is at 367.
Nov 05 06:42:58 myNode systemd[1]: electrs.service: Service RestartSec=1min expired, scheduling restart.
Nov 05 06:41:58 myNode systemd[1]: electrs.service: Failed with result 'exit-code'.
Nov 05 06:41:58 myNode systemd[1]: electrs.service: Main process exited, code=exited, status=1/FAILURE
Nov 05 06:41:58 myNode electrs[22863]:     2: receiving on an empty and disconnected channel
Nov 05 06:41:58 myNode electrs[22863]:     1: failed to get block 000000000000000000070742427fa10ec3c66d006160155a704d9f56d090a3ea
Nov 05 06:41:58 myNode electrs[22863]:     0: sync failed
Nov 05 06:41:58 myNode electrs[22863]: Caused by:
Nov 05 06:41:58 myNode electrs[22863]: Error: electrs failed
Nov 05 06:41:57 myNode electrs[22863]: [2022-11-05T11:41:57.979Z INFO  electrs::db] closing DB at /mnt/hdd/mynode/electrs/bitcoin
Nov 05 06:41:57 myNode electrs[22863]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 05 06:41:57 myNode electrs[22863]: thread 'p2p_recv' panicked at 'invalid message: OversizedVectorAllocation { requested: 12000072, max: 4000000 }', src/p2p.rs:211:62
Nov 05 06:41:57 myNode electrs[22863]: [2022-11-05T11:41:57.663Z INFO  electrs::index] indexing 581 blocks: [761241..761821]
Nov 05 06:41:57 myNode electrs[22863]: [2022-11-05T11:41:57.602Z INFO  electrs::chain] chain updated: tip=000000000000000000022fa13b5abb217c073ed005a73834cb886470af426678, height=761240
Nov 05 06:41:52 myNode electrs[22863]: [2022-11-05T11:41:52.708Z INFO  electrs::chain] loading 761240 headers, tip=000000000000000000022fa13b5abb217c073ed005a73834cb886470af426678
Nov 05 06:41:48 myNode electrs[22863]: [2022-11-05T11:41:48.363Z INFO  electrs::db] "/mnt/hdd/mynode/electrs/bitcoin": 1050 SST files, 56.664231347 GB, 4.696112756 Grows
Nov 05 06:41:48 myNode electrs[22863]: [2022-11-05T11:41:48.210Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
Nov 05 06:41:48 myNode electrs[22863]: [2022-11-05T11:41:48.210Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
Nov 05 06:41:48 myNode electrs[22863]: Starting electrs 0.9.3 on aarch64 linux with Config { network: Bitcoin, db_path: "/mnt/hdd/mynode/electrs/bitcoin", daemon_dir: "/home/bitcoin/.bitcoin", daemon_auth: CookieFile("/home/bitcoin/.bitcoin/.cookie"), daemon_rpc_addr: 127.0.0.1:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 15s, jsonrpc_timeout: 30s, index_batch_size: 10, index_lookup_limit: Some(200), reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.9.3 (Electrum Rust Server)!", args: [] }
Nov 05 06:41:48 myNode systemd[1]: Started myNode Electrum Server.
Nov 05 06:41:48 myNode electrs[22861]: + exit 0
Nov 05 06:41:48 myNode electrs[22861]: }
Nov 05 06:41:48 myNode electrs[22861]:   "warnings": ""
Nov 05 06:41:48 myNode electrs[22861]:   },
Nov 05 06:41:48 myNode electrs[22861]:     }
Nov 05 06:41:48 myNode electrs[22861]:       "active": true
Nov 05 06:41:48 myNode electrs[22861]:       "height": 709632,
Nov 05 06:41:48 myNode electrs[22861]:       },
Nov 05 06:41:48 myNode electrs[22861]:         "min_activation_height": 709632
Nov 05 06:41:48 myNode electrs[22861]:         "since": 709632,
Nov 05 06:41:48 myNode electrs[22861]:         "timeout": 1628640000,
Nov 05 06:41:48 myNode electrs[22861]:         "start_time": 1619222400,
Nov 05 06:41:48 myNode electrs[22861]:         "status": "active",
Nov 05 06:41:48 myNode electrs[22861]:       "bip9": {
Nov 05 06:41:48 myNode electrs[22861]:       "type": "bip9",
Nov 05 06:41:48 myNode electrs[22861]:     "taproot": {
Nov 05 06:41:48 myNode electrs[22861]:     },
Nov 05 06:41:48 myNode electrs[22861]:       "height": 481824
Nov 05 06:41:48 myNode electrs[22861]:       "active": true,
Nov 05 06:41:48 myNode electrs[22861]:       "type": "buried",
Nov 05 06:41:48 myNode electrs[22861]:     "segwit": {
Nov 05 06:41:48 myNode electrs[22861]:     },
Nov 05 06:41:48 myNode electrs[22861]:       "height": 419328
Nov 05 06:41:48 myNode electrs[22861]:       "active": true,
Nov 05 06:41:48 myNode electrs[22861]:       "type": "buried",
Nov 05 06:41:48 myNode electrs[22861]:     "csv": {
Nov 05 06:41:48 myNode electrs[22861]:     },
Nov 05 06:41:48 myNode electrs[22861]:       "height": 388381
Nov 05 06:41:48 myNode electrs[22861]:       "active": true,
Nov 05 06:41:48 myNode electrs[22861]:       "type": "buried",
Nov 05 06:41:48 myNode electrs[22861]:     "bip65": {
Nov 05 06:41:48 myNode electrs[22861]:     },
Nov 05 06:41:48 myNode electrs[22861]:       "height": 363725
Nov 05 06:41:48 myNode electrs[22861]:       "active": true,
Nov 05 06:41:48 myNode electrs[22861]:       "type": "buried",
Nov 05 06:41:48 myNode electrs[22861]:     "bip66": {
Nov 05 06:41:48 myNode electrs[22861]:     },
Nov 05 06:41:48 myNode electrs[22861]:       "height": 227931
Nov 05 06:41:48 myNode electrs[22861]:       "active": true,
Nov 05 06:41:48 myNode electrs[22861]:       "type": "buried",
Nov 05 06:41:48 myNode electrs[22861]:     "bip34": {
Nov 05 06:41:48 myNode electrs[22861]:   "softforks": {
Nov 05 06:41:48 myNode electrs[22861]:   "pruned": false,
Nov 05 06:41:48 myNode electrs[22861]:   "size_on_disk": 495654260974,
Nov 05 06:41:48 myNode electrs[22861]:   "chainwork": "000000000000000000000000000000000000000038ba89cfce49d11513aca6c2",
Nov 05 06:41:48 myNode electrs[22861]:   "initialblockdownload": false,
Nov 05 06:41:48 myNode electrs[22861]:   "verificationprogress": 0.9999966456945745,
Nov 05 06:41:48 myNode electrs[22861]:   "mediantime": 1667643988,
Nov 05 06:41:48 myNode electrs[22861]:   "difficulty": 36835682546787.98,
Nov 05 06:41:48 myNode electrs[22861]:   "bestblockhash": "00000000000000000000dd0d11630a583a7f7c16f5157bcc0910dfa70fedc689",
Nov 05 06:41:48 myNode electrs[22861]:   "headers": 761821,
Nov 05 06:41:48 myNode electrs[22861]:   "blocks": 761821,
Nov 05 06:41:48 myNode electrs[22861]:   "chain": "main",
Nov 05 06:41:48 myNode electrs[22861]: {
Nov 05 06:41:48 myNode electrs[22861]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
Nov 05 06:41:48 myNode electrs[22861]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoin_synced ']'
Nov 05 06:41:48 myNode electrs[22861]: Checking if Bitcoin is synced...
Nov 05 06:41:48 myNode electrs[22861]: + echo 'Checking if Bitcoin is synced...'
Nov 05 06:41:48 myNode electrs[22861]: + set -e
Nov 05 06:41:48 myNode electrs[22860]: Not shutting down!
Nov 05 06:41:48 myNode electrs[22860]: Checking if device is shutting down...
Nov 05 06:41:48 myNode systemd[1]: Starting myNode Electrum Server...
Nov 05 06:41:48 myNode systemd[1]: Stopped myNode Electrum Server.
Nov 05 06:41:48 myNode systemd[1]: electrs.service: Scheduled restart job, restart counter is at 366.
Nov 05 06:41:48 myNode systemd[1]: electrs.service: Service RestartSec=1min expired, scheduling restart.
Nov 05 06:40:47 myNode systemd[1]: electrs.service: Failed with result 'exit-code'.
Nov 05 06:40:47 myNode systemd[1]: electrs.service: Main process exited, code=exited, status=1/FAILURE
Nov 05 06:40:47 myNode electrs[21865]:     2: receiving on an empty and disconnected channel
Nov 05 06:40:47 myNode electrs[21865]:     1: failed to get block 000000000000000000070742427fa10ec3c66d006160155a704d9f56d090a3ea
Nov 05 06:40:47 myNode electrs[21865]:     0: sync failed
Nov 05 06:40:47 myNode electrs[21865]: Caused by:
Nov 05 06:40:47 myNode electrs[21865]: Error: electrs failed
Nov 05 06:40:47 myNode electrs[21865]: [2022-11-05T11:40:47.901Z INFO  electrs::db] closing DB at /mnt/hdd/mynode/electrs/bitcoin
Nov 05 06:40:47 myNode electrs[21865]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 05 06:40:47 myNode electrs[21865]: thread 'p2p_recv' panicked at 'invalid message: OversizedVectorAllocation { requested: 12000072, max: 4000000 }', src/p2p.rs:211:62
Nov 05 06:40:47 myNode electrs[21865]: [2022-11-05T11:40:47.652Z INFO  electrs::index] indexing 581 blocks: [761241..761821]
Nov 05 06:40:47 myNode electrs[21865]: [2022-11-05T11:40:47.608Z INFO  electrs::chain] chain updated: tip=000000000000000000022fa13b5abb217c073ed005a73834cb886470af426678, height=761240
Nov 05 06:40:42 myNode electrs[21865]: [2022-11-05T11:40:42.840Z INFO  electrs::chain] loading 761240 headers, tip=000000000000000000022fa13b5abb217c073ed005a73834cb886470af426678
Nov 05 06:40:38 myNode electrs[21865]: [2022-11-05T11:40:38.396Z INFO  electrs::db] "/mnt/hdd/mynode/electrs/bitcoin": 1049 SST files, 56.664230542 GB, 4.696112756 Grows
Nov 05 06:40:38 myNode electrs[21865]: [2022-11-05T11:40:38.222Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
Nov 05 06:40:38 myNode electrs[21865]: [2022-11-05T11:40:38.222Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
Nov 05 06:40:38 myNode electrs[21865]: Starting electrs 0.9.3 on aarch64 linux with Config { network: Bitcoin, db_path: "/mnt/hdd/mynode/electrs/bitcoin", daemon_dir: "/home/bitcoin/.bitcoin", daemon_auth: CookieFile("/home/bitcoin/.bitcoin/.cookie"), daemon_rpc_addr: 127.0.0.1:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 15s, jsonrpc_timeout: 30s, index_batch_size: 10, index_lookup_limit: Some(200), reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.9.3 (Electrum Rust Server)!", args: [] }
Nov 05 06:40:38 myNode systemd[1]: Started myNode Electrum Server.
Nov 05 06:40:38 myNode electrs[21862]: + exit 0
Nov 05 06:40:38 myNode electrs[21862]: }
Nov 05 06:40:38 myNode electrs[21862]:   "warnings": ""
Nov 05 06:40:38 myNode electrs[21862]:   },
Nov 05 06:40:38 myNode electrs[21862]:     }
Nov 05 06:40:38 myNode electrs[21862]:       "active": true
Nov 05 06:40:38 myNode electrs[21862]:       "height": 709632,
Nov 05 06:40:38 myNode electrs[21862]:       },
Nov 05 06:40:38 myNode electrs[21862]:         "min_activation_height": 709632
Nov 05 06:40:38 myNode electrs[21862]:         "since": 709632,
Nov 05 06:40:38 myNode electrs[21862]:         "timeout": 1628640000,
Nov 05 06:40:38 myNode electrs[21862]:         "start_time": 1619222400,
Nov 05 06:40:38 myNode electrs[21862]:         "status": "active",
Nov 05 06:40:38 myNode electrs[21862]:       "bip9": {
Nov 05 06:40:38 myNode electrs[21862]:       "type": "bip9",
Nov 05 06:40:38 myNode electrs[21862]:     "taproot": {
Nov 05 06:40:38 myNode electrs[21862]:     },
Nov 05 06:40:38 myNode electrs[21862]:       "height": 481824
Nov 05 06:40:38 myNode electrs[21862]:       "active": true,
Nov 05 06:40:38 myNode electrs[21862]:       "type": "buried",
Nov 05 06:40:38 myNode electrs[21862]:     "segwit": {
Nov 05 06:40:38 myNode electrs[21862]:     },
Nov 05 06:40:38 myNode electrs[21862]:       "height": 419328
Nov 05 06:40:38 myNode electrs[21862]:       "active": true,
Nov 05 06:40:38 myNode electrs[21862]:       "type": "buried",
Nov 05 06:40:38 myNode electrs[21862]:     "csv": {
Nov 05 06:40:38 myNode electrs[21862]:     },
Nov 05 06:40:38 myNode electrs[21862]:       "height": 388381
Nov 05 06:40:38 myNode electrs[21862]:       "active": true,
Nov 05 06:40:38 myNode electrs[21862]:       "type": "buried",
Nov 05 06:40:38 myNode electrs[21862]:     "bip65": {
Nov 05 06:40:38 myNode electrs[21862]:     },
Nov 05 06:40:38 myNode electrs[21862]:       "height": 363725
Nov 05 06:40:38 myNode electrs[21862]:       "active": true,
Nov 05 06:40:38 myNode electrs[21862]:       "type": "buried",
Nov 05 06:40:38 myNode electrs[21862]:     "bip66": {
Nov 05 06:40:38 myNode electrs[21862]:     },
Nov 05 06:40:38 myNode electrs[21862]:       "height": 227931
Nov 05 06:40:38 myNode electrs[21862]:       "active": true,
Nov 05 06:40:38 myNode electrs[21862]:       "type": "buried",
Nov 05 06:40:38 myNode electrs[21862]:     "bip34": {
Nov 05 06:40:38 myNode electrs[21862]:   "softforks": {
Nov 05 06:40:38 myNode electrs[21862]:   "pruned": false,
Nov 05 06:40:38 myNode electrs[21862]:   "size_on_disk": 495654260974,
Nov 05 06:40:38 myNode electrs[21862]:   "chainwork": "000000000000000000000000000000000000000038ba89cfce49d11513aca6c2",
Nov 05 06:40:38 myNode electrs[21862]:   "initialblockdownload": false,
Nov 05 06:40:38 myNode electrs[21862]:   "verificationprogress": 0.9999968639107857,
Nov 05 06:40:38 myNode electrs[21862]:   "mediantime": 1667643988,
Nov 05 06:40:38 myNode electrs[21862]:   "difficulty": 36835682546787.98,
Nov 05 06:40:38 myNode electrs[21862]:   "bestblockhash": "00000000000000000000dd0d11630a583a7f7c16f5157bcc0910dfa70fedc689",
Nov 05 06:40:38 myNode electrs[21862]:   "headers": 761821,
Nov 05 06:40:38 myNode electrs[21862]:   "blocks": 761821,
Nov 05 06:40:38 myNode electrs[21862]:   "chain": "main",
Nov 05 06:40:38 myNode electrs[21862]: {
Nov 05 06:40:38 myNode electrs[21862]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
Nov 05 06:40:38 myNode electrs[21862]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoin_synced ']'
Nov 05 06:40:38 myNode electrs[21862]: Checking if Bitcoin is synced...
Nov 05 06:40:38 myNode electrs[21862]: + echo 'Checking if Bitcoin is synced...'
Nov 05 06:40:38 myNode electrs[21862]: + set -e
Nov 05 06:40:38 myNode electrs[21861]: Not shutting down!
Nov 05 06:40:38 myNode electrs[21861]: Checking if device is shutting down...
Nov 05 06:40:38 myNode systemd[1]: Starting myNode Electrum Server...
Nov 05 06:40:38 myNode systemd[1]: Stopped myNode Electrum Server.
Nov 05 06:40:38 myNode systemd[1]: electrs.service: Scheduled restart job, restart counter is at 365.
Nov 05 06:40:38 myNode systemd[1]: electrs.service: Service RestartSec=1min expired, scheduling restart.
Nov 05 06:39:38 myNode systemd[1]: electrs.service: Failed with result 'exit-code'.
Nov 05 06:39:38 myNode systemd[1]: electrs.service: Main process exited, code=exited, status=1/FAILURE
Nov 05 06:39:38 myNode electrs[20872]:     2: receiving on an empty and disconnected channel
Nov 05 06:39:38 myNode electrs[20872]:     1: failed to get block 000000000000000000070742427fa10ec3c66d006160155a704d9f56d090a3ea
Nov 05 06:39:38 myNode electrs[20872]:     0: sync failed
Nov 05 06:39:38 myNode electrs[20872]: Caused by:
Nov 05 06:39:38 myNode electrs[20872]: Error: electrs failed
Nov 05 06:39:38 myNode electrs[20872]: [2022-11-05T11:39:38.046Z INFO  electrs::db] closing DB at /mnt/hdd/mynode/electrs/bitcoin
Nov 05 06:39:37 myNode electrs[20872]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 05 06:39:37 myNode electrs[20872]: thread 'p2p_recv' panicked at 'invalid message: OversizedVectorAllocation { requested: 12000072, max: 4000000 }', src/p2p.rs:211:62
Nov 05 06:39:37 myNode electrs[20872]: [2022-11-05T11:39:37.829Z INFO  electrs::index] indexing 581 blocks: [761241..761821]
Nov 05 06:39:37 myNode electrs[20872]: [2022-11-05T11:39:37.786Z INFO  electrs::chain] chain updated: tip=000000000000000000022fa13b5abb217c073ed005a73834cb886470af426678, height=761240
Nov 05 06:39:33 myNode electrs[20872]: [2022-11-05T11:39:33.126Z INFO  electrs::chain] loading 761240 headers, tip=000000000000000000022fa13b5abb217c073ed005a73834cb886470af426678
Nov 05 06:39:28 myNode electrs[20872]: [2022-11-05T11:39:28.375Z INFO  electrs::db] "/mnt/hdd/mynode/electrs/bitcoin": 1048 SST files, 56.664229737 GB, 4.696112756 Grows
Nov 05 06:39:28 myNode electrs[20872]: [2022-11-05T11:39:28.225Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
Nov 05 06:39:28 myNode electrs[20872]: [2022-11-05T11:39:28.225Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
Nov 05 06:39:28 myNode electrs[20872]: Starting electrs 0.9.3 on aarch64 linux with Config { network: Bitcoin, db_path: "/mnt/hdd/mynode/electrs/bitcoin", daemon_dir: "/home/bitcoin/.bitcoin", daemon_auth: CookieFile("/home/bitcoin/.bitcoin/.cookie"), daemon_rpc_addr: 127.0.0.1:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 15s, jsonrpc_timeout: 30s, index_batch_size: 10, index_lookup_limit: Some(200), reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.9.3 (Electrum Rust Server)!", args: [] }
Nov 05 06:39:28 myNode systemd[1]: Started myNode Electrum Server.
Nov 05 06:39:28 myNode electrs[20870]: + exit 0
Nov 05 06:39:28 myNode electrs[20870]: }
Nov 05 06:39:28 myNode electrs[20870]:   "warnings": ""
Nov 05 06:39:28 myNode electrs[20870]:   },
Nov 05 06:39:28 myNode electrs[20870]:     }
Nov 05 06:39:28 myNode electrs[20870]:       "active": true
Nov 05 06:39:28 myNode electrs[20870]:       "height": 709632,
Nov 05 06:39:28 myNode electrs[20870]:       },
Nov 05 06:39:28 myNode electrs[20870]:         "min_activation_height": 709632
Nov 05 06:39:28 myNode electrs[20870]:         "since": 709632,
Nov 05 06:39:28 myNode electrs[20870]:         "timeout": 1628640000,
Nov 05 06:39:28 myNode electrs[20870]:         "start_time": 1619222400,
Nov 05 06:39:28 myNode electrs[20870]:         "status": "active",
Nov 05 06:39:28 myNode electrs[20870]:       "bip9": {
Nov 05 06:39:28 myNode electrs[20870]:       "type": "bip9",
Nov 05 06:39:28 myNode electrs[20870]:     "taproot": {
Nov 05 06:39:28 myNode electrs[20870]:     },
Nov 05 06:39:28 myNode electrs[20870]:       "height": 481824
Nov 05 06:39:28 myNode electrs[20870]:       "active": true,
Nov 05 06:39:28 myNode electrs[20870]:       "type": "buried",
Nov 05 06:39:28 myNode electrs[20870]:     "segwit": {
Nov 05 06:39:28 myNode electrs[20870]:     },
Nov 05 06:39:28 myNode electrs[20870]:       "height": 419328
Nov 05 06:39:28 myNode electrs[20870]:       "active": true,
Nov 05 06:39:28 myNode electrs[20870]:       "type": "buried",
Nov 05 06:39:28 myNode electrs[20870]:     "csv": {
Nov 05 06:39:28 myNode electrs[20870]:     },
Nov 05 06:39:28 myNode electrs[20870]:       "height": 388381
Nov 05 06:39:28 myNode electrs[20870]:       "active": true,
Nov 05 06:39:28 myNode electrs[20870]:       "type": "buried",
Nov 05 06:39:28 myNode electrs[20870]:     "bip65": {
Nov 05 06:39:28 myNode electrs[20870]:     },

```

**Comment by tehelsper** [comment]
Upgrade to v0.3.04. If you are on RP4 32-bit, you can re-flash to the 64-bit OS or install the latest beta for a fix.
