### ISSUE TITLE
electrum server stuck syncing

### ISSUE THREAD

**Issue by MotaySalem** [mynodebtc/mynode#723]
**Describe the bug:**
Hello everyone,
my electrum server stuck syncing at 98.84%. Until the end of syncing it went really smooth, but unfortunately I got this error:

**Expected behavior**
Full sync of electrum server

**MyNode hardware (please complete the following information):**
Raspi4, 4 GB version
MyNode version 0.3.03
Electrum server version 0.9.3

**Error log from electrs:**
-- Logs begin at Wed 2022-11-09 14:29:06 CST, end at Wed 2022-11-09 22:47:31 CST. --
Nov 09 22:46:39 myNode systemd[1]: electrs.service: Failed with result 'exit-code'.
Nov 09 22:46:39 myNode systemd[1]: electrs.service: Main process exited, code=exited, status=1/FAILURE
Nov 09 22:46:39 myNode electrs[22769]:     2: receiving on an empty and disconnected channel
Nov 09 22:46:39 myNode electrs[22769]:     1: failed to get block 000000000000000000070742427fa10ec3c66d006160155a704d9f56d090a3ea
Nov 09 22:46:39 myNode electrs[22769]:     0: sync failed
Nov 09 22:46:39 myNode electrs[22769]: Caused by:
Nov 09 22:46:39 myNode electrs[22769]: Error: electrs failed
Nov 09 22:46:39 myNode electrs[22769]: [2022-11-10T04:46:39.585Z INFO  electrs::db] closing DB at /mnt/hdd/mynode/electrs/bitcoin
Nov 09 22:46:39 myNode electrs[22769]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 09 22:46:39 myNode electrs[22769]: thread 'p2p_recv' panicked at 'invalid message: OversizedVectorAllocation { requested: 12000072, max: 4000000 }', src/p2p.rs:211:62
Nov 09 22:46:39 myNode electrs[22769]: [2022-11-10T04:46:39.337Z INFO  electrs::index] indexing 1282 blocks: [761241..762522]
Nov 09 22:46:39 myNode electrs[22769]: [2022-11-10T04:46:39.285Z INFO  electrs::chain] chain updated: tip=000000000000000000022fa13b5abb217c073ed005a73834cb886470af426678, height=761240
Nov 09 22:46:34 myNode electrs[22769]: [2022-11-10T04:46:34.612Z INFO  electrs::chain] loading 761240 headers, tip=000000000000000000022fa13b5abb217c073ed005a73834cb886470af426678
Nov 09 22:46:30 myNode electrs[22769]: [2022-11-10T04:46:30.314Z INFO  electrs::db] "/mnt/hdd/mynode/electrs/bitcoin": 1286 SST files, 56.665794056 GB, 4.696112756 Grows
Nov 09 22:46:30 myNode electrs[22769]: [2022-11-10T04:46:30.158Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
Nov 09 22:46:30 myNode electrs[22769]: [2022-11-10T04:46:30.158Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
Nov 09 22:46:30 myNode electrs[22769]: Starting electrs 0.9.3 on aarch64 linux with Config { network: Bitcoin, db_path: "/mnt/hdd/mynode/electrs/bitcoin", daemon_dir: "/home/bitcoin/.bitcoin", daemon_auth: CookieFile("/home/bitcoin/.bitcoin/.cookie"), daemon_rpc_addr: 127.0.0.1:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 15s, jsonrpc_timeout: 30s, index_batch_size: 10, index_lookup_limit: Some(200), reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.9.3 (Electrum Rust Server)!", args: [] }
Nov 09 22:46:30 myNode systemd[1]: Started myNode Electrum Server.
Nov 09 22:46:30 myNode electrs[22767]: + exit 0
Nov 09 22:46:30 myNode electrs[22767]: }
Nov 09 22:46:30 myNode electrs[22767]:   "warnings": ""
Nov 09 22:46:30 myNode electrs[22767]:   "pruned": false,
Nov 09 22:46:30 myNode electrs[22767]:   "size_on_disk": 496570459534,
Nov 09 22:46:30 myNode electrs[22767]:   "chainwork": "000000000000000000000000000000000000000039162739f848f42c25d4a84c",
Nov 09 22:46:30 myNode electrs[22767]:   "initialblockdownload": false,
Nov 09 22:46:30 myNode electrs[22767]:   "verificationprogress": 0.9999958479205118,
Nov 09 22:46:30 myNode electrs[22767]:   "mediantime": 1668053437,
Nov 09 22:46:30 myNode electrs[22767]:   "time": 1668054471,
Nov 09 22:46:30 myNode electrs[22767]:   "difficulty": 36762198818467.21,
Nov 09 22:46:30 myNode electrs[22767]:   "bestblockhash": "00000000000000000000df88900fdf7da8b00630d8a3ab144e049a9e3011f5b3",
Nov 09 22:46:30 myNode electrs[22767]:   "headers": 762522,
Nov 09 22:46:30 myNode electrs[22767]:   "blocks": 762522,
Nov 09 22:46:30 myNode electrs[22767]:   "chain": "main",
Nov 09 22:46:30 myNode electrs[22767]: {
Nov 09 22:46:30 myNode electrs[22767]: + bitcoin-cli -datadir=/mnt/hdd/mynode/bitcoin -rpcwait getblockchaininfo
Nov 09 22:46:30 myNode electrs[22767]: + '[' '!' -f /mnt/hdd/mynode/.mynode_bitcoin_synced ']'
Nov 09 22:46:30 myNode electrs[22767]: Checking if Bitcoin is synced...
Nov 09 22:46:30 myNode electrs[22767]: + echo 'Checking if Bitcoin is synced...'
Nov 09 22:46:30 myNode electrs[22767]: + set -e
Nov 09 22:46:30 myNode electrs[22766]: Not shutting down!
Nov 09 22:46:30 myNode electrs[22766]: Checking if device is shutting down...
Nov 09 22:46:30 myNode systemd[1]: Starting myNode Electrum Server...
Nov 09 22:46:30 myNode systemd[1]: Stopped myNode Electrum Server.
Nov 09 22:46:30 myNode systemd[1]: electrs.service: Scheduled restart job, restart counter is at 423.
Nov 09 22:46:30 myNode systemd[1]: electrs.service: Service RestartSec=1min expired, scheduling restart.
Nov 09 22:45:29 myNode systemd[1]: electrs.service: Failed with result 'exit-code'.
Nov 09 22:45:29 myNode systemd[1]: electrs.service: Main process exited, code=exited, status=1/FAILURE
Nov 09 22:45:29 myNode electrs[22438]:     2: receiving on an empty and disconnected channel
Nov 09 22:45:29 myNode electrs[22438]:     1: failed to get block 000000000000000000070742427fa10ec3c66d006160155a704d9f56d090a3ea
Nov 09 22:45:29 myNode electrs[22438]:     0: sync failed
Nov 09 22:45:29 myNode electrs[22438]: Caused by:
Nov 09 22:45:29 myNode electrs[22438]: Error: electrs failed
Nov 09 22:45:29 myNode electrs[22438]: [2022-11-10T04:45:29.935Z INFO  electrs::db] closing DB at /mnt/hdd/mynode/electrs/bitcoin
Nov 09 22:45:29 myNode electrs[22438]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 09 22:45:29 myNode electrs[22438]: thread 'p2p_recv' panicked at 'invalid message: OversizedVectorAllocation { requested: 12000072, max: 4000000 }', src/p2p.rs:211:62
Nov 09 22:45:29 myNode electrs[22438]: [2022-11-10T04:45:29.716Z INFO  electrs::index] indexing 1282 blocks: [761241..762522]
Nov 09 22:45:29 myNode electrs[22438]: [2022-11-10T04:45:29.669Z INFO  electrs::chain] chain updated: tip=000000000000000000022fa13b5abb217c073ed005a73834cb886470af426678, height=761240
Nov 09 22:45:25 myNode electrs[22438]: [2022-11-10T04:45:25.040Z INFO  electrs::chain] loading 761240 headers, tip=000000000000000000022fa13b5abb217c073ed005a73834cb886470af426678
Nov 09 22:45:20 myNode electrs[22438]: [2022-11-10T04:45:20.758Z INFO  electrs::db] "/mnt/hdd/mynode/electrs/bitcoin": 1285 SST files, 56.665793251 GB, 4.696112756 Grows
Nov 09 22:45:20 myNode electrs[22438]: [2022-11-10T04:45:20.624Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
Nov 09 22:45:20 myNode electrs[22438]: [2022-11-10T04:45:20.624Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
Nov 09 22:45:20 myNode electrs[22438]: Starting electrs 0.9.3 on aarch64 linux with Config { network: Bitcoin, db_path: "/mnt/hdd/mynode/electrs/bitcoin", daemon_dir: "/home/bitcoin/.bitcoin", daemon_auth: CookieFile("/home/bitcoin/.bitcoin/.cookie"), daemon_rpc_addr: 127.0.0.1:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 15s, jsonrpc_timeout: 30s, index_batch_size: 10, index_lookup_limit: Some(200), reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.9.3 (Electrum Rust Server)!", args: [] }
Nov 09 22:45:20 myNode systemd[1]: Started myNode Electrum Server.

Can somebody help me debugging this issue ?
I`ve already tried and add local IPs to Bitcoin.conf. 
Should I upgrade MyNode and electrs ?

**Comment by MotaySalem** [comment]
oh man. upgrading MyNode solved the issue.
